version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: cimg/base:2023.06
    resource_class: large
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker login
          command: docker login --username=blinker --password=$DOCKERHUB_PASSWORD
      - run: .circleci/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
          context:
            - dockerhub
