version: 2

jobs:
  build_and_deploy:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: blinker
          password: $DOCKERHUB_PASSWORD
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.11
      - run: .circleci/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          # We have to explicitly tell CircleCi to run on all tags and branches, or tag commits/pushes will not trigger
          # builds: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution.
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
